name: docker image building and pushing

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches: [ master ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 5,17 * * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:  
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push alpine
        uses: docker/build-push-action@v3
        with:
          context: dockerfiles/alpine
          platforms: linux/arm/v7,linux/arm/v6
          push: true
          tags: gounthar/gitlab-runner:alpine-arm
      -
        name: Build and push latest
        uses: docker/build-push-action@v3
        with:
          context: dockerfiles/alpine
          platforms: linux/arm/v7,linux/arm/v6
          push: true
          tags: gounthar/gitlab-runner
      -
        name: Build and push Ubuntu
        uses: docker/build-push-action@v3
        with:
          context: dockerfiles/ubuntu
          platforms: linux/arm/v7
          push: true
          tags: gounthar/gitlab-runner:ubuntu
      -
        name: Build and push latest arm
        uses: docker/build-push-action@v3
        with:
          context: dockerfiles/ubuntu
          platforms: linux/arm/v7
          push: true
          tags: gounthar/gitlab-runner:latest-arm
